@startuml
'https://plantuml.com/class-diagram


class Pokemon{
   -all other attributes
   -weatherCondition: String



   +all other methods
   +createWeather(weather: name): void
}

class Weather{
    -weather: string
    -duration: int
    +initialize(name: String, duration: int): Weather
    +createWeather(weatherName: string, duration: int): void
}
@enduml