######################################################################
# This file copyright the Georgia Institute of Technology
#
# Permission is given to students to use or modify this file (only)
# to work on their assignments.
#
# You may NOT publish this file or make it available to others not in
# the course.
#
######################################################################

import math


class IndianaDronesPartATestCases:
    test_case_1 = {'test_case': 1,
                   'area_map': ['..........',
                                '........*.',
                                '...B......',
                                '..........',
                                '..........',
                                'A..@...C..',
                                '..........',
                                '..........',
                                '..........',
                                '..........'],
                   'tree_radius' : {'A' : 0.5, 'B' : 0.2, 'C':0.3},
                   'move': ['move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963'],
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'drone_tolerance': 0.25,
                   'landmark_tolerance': 0.25,
                   'horizon' : float('inf')}
        
    test_case_2 = {'test_case': 2,
                    'area_map': ['..........',
                                'A.B.D.E..C',
                                '....*.....',
                                'M......K..',
                                '...@......',
                                '..N......L',
                                '..........',
                                'O.........',
                                'F.HIJ.TR..',
                                '..........',],
                    'tree_radius' : {'A' : 0.2, 'B' : 0.2, 'C': 0.2,'D':0.3, 'E':0.2, 'F' : 0.5, 'H' : 0.2, 'I': 0.4,'J':0.2, 'K':0.8, 'L' : 0.1, 'M' : 0.7, 'N': 0.3,'O':0.3, 'R':0.5, 'T':0.4},
                    'move': ['move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963'],
                    'drone_distance_noise': 0.05,
                    'drone_bearing_noise': 0.03,
                    'drone_tolerance': 0.25,
                    'landmark_tolerance': 0.25,
                    'horizon' : float('inf')}

    test_case_3 = {'test_case': 3,
                    'area_map': ['..........',
                                '.QR..HID.V',
                                '..*.......',
                                '....G..X..',
                                '..........',
                                '.A..C..Y..',
                                '...V.@...Z',
                                '..........',
                                '..........',
                                'O.B.FBCM..',],
                    'tree_radius' : {'A' : 0.3, 'B' : 0.5, 'C': 0.7, 'D': 0.3, 'F' : 0.5, 'G' : 0.2, 'H' : 0.3, 'I': 0.4, 'M' : 0.1, 'O':0.7, 'Q' : 0.2,'R':0.5, 'V': 0.3, 'X': 0.2, 'Y': 0.1, 'Z':0.5},
                                
                    'move': ['move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0'],
                    'drone_distance_noise': 0.05,
                    'drone_bearing_noise': 0.03,
                    'drone_tolerance': 0.25,
                    'landmark_tolerance': 0.25,
                    'horizon' : float('inf')}

    test_case_4 = {'test_case': 4,
                   'area_map': ['..........',
                                '...L......',
                                '..........',
                                '...A..*...',
                                '..........',
                                '......@...',
                                '..........',
                                '...D......',
                                '..........',
                                '......M...'],
                    
                    'tree_radius' : {'A' : 0.3, 'D': 0.2, 'L': 0.4, 'M' : 0.1},

                   'move': ['move 0.0 1.570963',
                            'move 0.0 1.570963',
                            'move 1.0 0.785481',
                            'move 0.5 0.0',
                            'move 0.5 0.0',
                            'move 0.5 1.0',
                            'move 0.5 0.0'],
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'drone_tolerance': 0.25,
                   'landmark_tolerance': 0.25,
                   'horizon' : 5.0}

    test_case_5 = {'test_case': 5,
                   'area_map': ['J.A.MN..OC',
                                '..........',
                                'D....L..P.',
                                '..........',
                                'G.@......K',
                                '.....B....',
                                '.H......Q.',
                                '..........',
                                'I..E..R...',
                                '.......*..'],
                    'tree_radius' : {'J' : 0.1, 'A' : 0.3, 'M' : 0.2, 'N' : 0.3, 'O' : 0.3,'C' : 0.3,'D' : 0.1,'L' : 0.3,'P' : 0.7,'G' : 0.3,'B' : 0.5, 'K' : 0.6, 'H' : 0.5, 'Q' : 0.3, 'I' : 0.3, 'E' : 0.3, 'R' : 0.2,},

                   'move': ['move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 1.570963',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 0.5 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 0.0',
                            'move 1.0 1.570963',
                            'move 1.0 1.570963',
                            'move 1.0 0.0',
                            'move 1.0 -1.570963',
                            'move 1.0 0.0',
                            'move 1.0 0.0',],
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'drone_tolerance': 0.25,
                   'landmark_tolerance': 0.25,
                   'horizon' : 3.0}

    all_cases = [
        test_case_1,
        # test_case_2,
        # test_case_3,
        # test_case_4,
        # test_case_5
    ]

class IndianaDronesPartBTestCases:

    test_case_1 = {'test_case': 1, 
                   'area_map': ['..........',
                                '....*.D...',
                                '..........',
                                '....B.....',
                                '..........',
                                '..A...C...',
                                '....@.....',
                                '..........',
                                '..........',
                                '..........'],
                   'tree_radius' : {'A' : 0.5, 'B' : 0.5, 'C': 0.3, 'D': 0.2},
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'max_distance': 2.0,
                   'max_steering': math.pi / 2. + 0.01,
                   'horizon': 3}
        
    test_case_2 = {'test_case': 2,
                   'area_map': ['....G....K',
                                '.J....I..@',
                                '...H....A.',
                                '.......P..',
                                '...F......',
                                '.....M...B',
                                '.C..*.E...',
                                '...L......',
                                '..D..N..O.',
                                '..........'],
                   'tree_radius' : {'A' : 0.7, 'B' : 0.6, 'C':0.7, 'D': 0.3, 'E': 0.2, 'F': 0.4, 'G' : 0.2, 'H' : 0.3, 'I' : 0.3, 'J' : 0.5, 'K' : 0.3, 'L' : 0.4, 'M' : 0.2, 'N': 0.6, 'O' : 0.3, 'P' : 0.2},
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'max_distance': 1.5,
                   'max_steering': math.pi / 2. + 0.01,
                   'horizon': 4}

    test_case_3 = {'test_case': 3,
                   'area_map': ['...N......',
                                '..........',
                                '.D...E.F..',
                                '...P..*...',
                                '.A...G....',
                                '..O...L.H.',
                                '..........',
                                'C.I..J....',
                                '.@.K....M.',
                                'Q.B........'],
                   'tree_radius' : {'A' : 0.2, 'B' : 0.2, 'C':0.4, 'D': 0.3, 'E': 0.7, 'F': 0.4, 'G' : 0.2, 'H' : 0.5, 'I' : 0.4, 'J': 0.3, 'K': 0.2, 'L': 0.1, 'M': 0.4, 'N' : 0.5, 'O' : 0.2, 'P' : 0.1, 'Q' : 0.3},
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'max_distance': 1.8,
                   'max_steering': math.pi / 2. + 0.01,
                   'horizon': 2.7}

    test_case_4 = {'test_case': 4, 
                   'area_map': ['......B.S.',
                                '.D..N...@.',
                                '.......F..',
                                '.......E.R',
                                'O..L..U...',
                                '..P....H.Y',
                                '.I.J......',
                                'A.*.K.V..Z',
                                '..Q....T.X',
                                '.C...M..W.'],
                   'tree_radius' : {'A' : 0.2, 'B' : 0.2, 'C':0.4, 'D': 0.3, 'E': 0.4, 'F': 0.4, 'H' : 0.6, 'I' : 0.2, 'J': 0.3, 'K': 0.5, 'L': 0.3, 'M': 0.4, 'N' : 0.5, 'O' : 0.4, 'P' : 0.6, 'Q' : 0.3, 'R' : 0.5, 'S' : 0.6, 'T' : 0.2, 'U' : 0.2, 'V' : 0.4, 'W' : 0.2, 'X' : 0.5, 'Y' : 0.2, 'Z' : 0.2},
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'max_distance': 2.5,
                   'max_steering': math.pi / 2. + 0.01,
                   'horizon': 3}

    test_case_5 = {'test_case': 5, 
                   'area_map': ['N..B.V....',
                                '..D....T..',
                                '@....E.F..',
                                '...P....R.',
                                'O.C..G.U..',
                                '....L.A.*.',
                                '...Q..H...',
                                '.....J....',
                                '...K....M.',
                                '.......S..'],
                   'tree_radius' : {'A' : 0.2, 'B' : 0.2, 'C':0.4, 'D': 0.2, 'E': 0.3, 'F': 0.3, 'G' : 0.2, 'H' : 0.4, 'J': 0.3, 'K': 0.3, 'L': 0.1, 'M': 0.4, 'N' : 0.5, 'O' : 0.2, 'P' : 0.3, 'Q' : 0.3, 'R' : 0.2, 'S' : 0.5, 'T' : 0.2, 'U' : 0.5, 'V' : 0.5},
                   'drone_distance_noise': 0.05,
                   'drone_bearing_noise': 0.03,
                   'max_distance': 1.5,
                   'max_steering': math.pi / 2. + 0.01,
                   'horizon': 2.0}

    
    all_cases = [
        test_case_1,
        test_case_2,
        test_case_3,
        test_case_4,
        test_case_5,
    ]
