name: ml4t
dependencies:
- python=3.10
- cycler=0.11
- kiwisolver=1.4.2
- matplotlib=3.5
- numpy=1.22.3
- pandas=1.4.3
- pyparsing=3.0.4
- python-dateutil=2.8
- pytz=2022.1
- scipy=1.7.3
- seaborn=0.11.2
- six=1.16.0
- joblib=1.1.0
- pytest=7.1.2
- future=0.18.2
- pip
- pip:
  - pprofile==2.1.0
  - jsons==1.6.3
  - gradescope-utils